- contracts/CapabilityGrants.cdc
Path to 3 stage custody.  ( dapp custody, shared custody, user custody ) 
Child account has a resource to manage saving resources and linking saved resources when saving. 
From this resource you can create an OwnerResource and AppResource. 
OwnerResource manages App's access to capabilities ( can grant and remove capabilities ) 
AppResource can access to granted capabilities. 
Missing Pieces:
- By returning and destroying the OwnerResource, Owner can get full custody.
> Shared custody and grant management

- contracts/CapabilityFilter.cdc
- contracts/CapabilityProxy.cdc
- contracts/HybridCustody.cdc
Closes: #15
Adding events to HybridCustody, CapabilityProxy, and CapabilityFilter contracts. The initial form of this PR should not be taken as prescriptive or final, but as a concrete starting point to drive discussions around the topic and quickly iterate on if needed.
At a high level, we want a user to know:
1. When they have an account available to claim
2. When they have successfully claimed said account access
3. Identifying info about the resources involved in their access on an account
4. When their account has been removed, either by their direct action or by another party with the ability to do so
5. When a Capability has been added/removed to/from a relevant CapabilityProxy
6. When a new Type has been added/removed to/from a relevant CapabilityFilter
7. When they have been …
> Add events to contract suite

- scripts/hybrid-custody/get_all_flow_balances.cdc
- scripts/hybrid-custody/get_all_vault_bal_from_storage.cdc
- scripts/hybrid-custody/get_spec_balance_from_public.cdc
- scripts/test/get_all_vault_bal_from_storage.cdc
- scripts/test/get_flow_balance.cdc
- test/HybridCustody_tests.cdc
Related: #26
Note about test coverage - I was having difficulty getting `scriptExecutor()` to return the `{Address: {Type: UFix64}}` from `get_all_vault_bal_from_storage`. I kept running into the following error when executing the script despite successful manual testing:
```
- FAIL: testGetAllFTBalance
Execution failed:
error: assertion failed: Failed to execute the script because -:  cannot import dictionary: keys does not belong to the same type
--> 7465737400000000000000000000000000000000000000000000000000000000:518:4
```
This occurred with and without casting the return value, which makes me wonder if it's something funky going on with the test framework.
Regardless, wanted to get this PR in before EOD.
> Add FungibleToken balance queries

- flow.json
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/onboarding/blockchain-native.cdc
Related: #50
Adds a multisig blockchain-native onboarding transaction that:
1. Creates a new dev-funded account
2. Configures a `ChildAccount` in the new account
3. Configures a `HybridCustody.Manager` in the signing parent account (if needed)
4. Adds a `ProxyAccount` Capability on the new account to the parent's `Manager`
The ultimate result is a new account that is linked to the signing parent in a single mulitisig transaction. Pre-requisites for this transaction include configuring Filter Manager & Factory resources & Capabilities, the addresses for which are provided as transaction args along with the public key hex to add on the new account and amount of $FLOW to seed to the new account.
> Add blockchain-native onboarding transaction

- contracts/HybridCustody.cdc
- transactions/hybrid-custody/accept_ownership.cdc
The Account type flip found [here](https://github.com/onflow/flips/pull/92) is set to define a new type which will cause a conflict in our own type definitions. AuthAccount is going to be split into a set of interfaces and a concrete called `Account` which we also define. If the flip were to be implemented, that type would brick our own contract due to `Account` being a reserved type/keyword.
Since we aren't in mainnet yet, we can rename the type here and avoid the conflict entirely.
> rename Account interface to OwnedAccount

- contracts/CapabilityProxy.cdc
- scripts/proxy/find_nft_provider_cap.cdc
- scripts/proxy/get_all_private_caps.cdc
- scripts/proxy/get_all_public_caps.cdc
- scripts/proxy/get_nft_provider.cdc
- test/CapabilityProxy_tests.cdc
- transactions/proxy/add_private_nft_collection.cdc
Closes: #60
Fixing return value for `CapabilityProxy.Proxy.getAllPrivate()` to return privateCapabilities and add test case coverage for both public and private return values.
> fix CapabilityProxy.Proxy.getAllPrivate + test coverage

- contracts/CapabilityFilter.cdc
- scripts/proxy/get_all_private_caps.cdc
- scripts/proxy/get_all_public_caps.cdc
- test/CapabilityProxy_tests.cdc
Related: #61
Updating `DenylistFilter.allowed()` to return false on invalid Capabilities. Also fixing failing `CapabilityProxy` test cases & supporting scripts.
> Fix denylist filter

- contracts/HybridCustody.cdc
- scripts/test/create_manager_with_invalid_filter.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/accept_ownership.cdc
- transactions/hybrid-custody/add_example_nft2_collection_to_proxy.cdc
- transactions/hybrid-custody/add_example_nft_collection_to_proxy.cdc
- transactions/hybrid-custody/onboarding/blockchain_native.cdc
- transactions/hybrid-custody/redeem_account.cdc
- transactions/hybrid-custody/setup_multi_sig.cdc
Closes: #63
Added checks on Capability parameters throughout the HybridCustody contract, along with test coverage for Manager init values. I realize some of these checks are redundant (e.g. `HybridCustody.createManager()` flowing through to `Manager.init()`), but helpful for readability.
> add capability checks & test coverage in HybridCustody

- contracts/CapabilityFactory.cdc
- contracts/CapabilityFilter.cdc
- contracts/CapabilityProxy.cdc
- contracts/HybridCustody.cdc
- scripts/factory/get_supported_types_from_manager.cdc
- scripts/test/add_nft_provider_factory.cdc
- scripts/test/remove_nft_provider_factory.cdc
- scripts/test/update_nft_provider_factory.cdc
- test/CapabilityFactory_tests.cdc
- transactions/factory/setup.cdc
Closes: #73 
Coverage: 75.6%
Added pre condition to `Manager.addFactory()` to prevent overwriting existing factories. Also added `Manager.updateFactory()` which overwrites Factories on given Type, and adds if it didn't already exist. The thought here is that the behavior is more explicit and provides a safer method to add new Factory types depending on developer preference, but open to feedback on this behavior.
Also added comments to CapabilityFactory contract.
Last note, I added a delimiter `'_'` to derived canonical paths between the prefix and deployment Address. I thought this would make it easier to split the strings should the need arise.
> Update CapabilityFactory Manager

- contracts/HybridCustody.cdc
- flow.json
- scripts/hybrid-custody/get_pending_owner_of_child.cdc
- test/HybridCustody_tests.cdc
Closes: #65
Coverage: 75.2%
Assigning owner similar to pattern for assigning `ProxyAccount` parent with `setOwnerCallback(_ addr: Address)` added to `OwnedAccount` interface. This callback both sets the `ChildAccount.acctOwner` as the address of the calling `Manager` and clears the new `ChildAccount.pendingOwner` field. This new field enables onchain state to reflect the in-flight transfer of ownership status and ensure that the correct user is set as the owner.
> Fix owner assignment

- .gitignore
- contracts/HybridCustody.cdc
- transactions/hybrid-custody/accept_ownership.cdc
Closes #74
1. Removes TODOs which (I think) have already been resolved
2. Handles a TODO about letting the owner of an account rotate the auth account capability
3. Leaves one TODO (happy to address in this PR) about how to handle publishing to a parent a second time.
> address outstanding TODOs

- contracts/HybridCustody.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/transfer_ownership_from_manager.cdc
Closes: #94 
Renaming from `Manager.giveOwnerShip()` to `Manager.giveOwnership()` and adding test coverage for the method.
> add coverage for Manager.giveOwnership()

- transactions/hybrid-custody/setup_multi_sig.cdc
The multi sig linking & parent setup TX does not link the public manager capability to the correctly public path.  This causes failures when later using other hybrid custody interactions
closes #133
> Fix multi-sig linking transaction

- README.md
This will add two badges in the `README`, as shown below:
> Add badges in `README` for integration tests and code coverage

- .gitignore
- README.md
- flow.json
Related: #155
Adds hosted Factory/Filter details to README as well as Filter details to flow config. This is after configuring NFT, FT, & NFT+FT related Factory Managers as well as AllowAllFilter at the listed addresses on Testnet.
> Add Deployment & Hosted Filter/Factory Details

- contracts/HybridCustody.cdc
- scripts/test/can_get_child_factory_and_filter_caps.cdc
- test/HybridCustody_tests.cdc
Without this, it's very difficult to detect whether a certain capability is allowed to be retrieved unless you run scripts manually. With helper methods like this (I'm sure others will be needed), you can borrow and return details of the filter/factory yourself and then process them offline
> Extend AccountPublic to allow retrieval of Factory and Filter capabilities

- .github/workflows/integration-tests.yml
- contracts/HybridCustody.cdc
When `giveOwnership` and `addOwnedAccount` are executed in the same transaction
`rotateAuthAccount` will be called twice.
However, during the second call, since authAcctPath is the same, it will cause `acct.linkAccount` to return `nil` as a result.
Personal opinion, it would be better to change `HybridCustody` overall to CapCons coding style.
> Fix: rotateAuthAccount failed when called twice

- contracts/HybridCustody.cdc
- scripts/test/get_nft_provider_capability_optional.cdc
- test/CapabilityFactory_tests.cdc
- test/HybridCustody_tests.cdc
- test/test_helpers.cdc
> update .getCapability() to return nil if cap disallowed + tests

- .github/workflows/integration-tests.yml
- contracts/factories/NFTCollectionFactory.cdc
Closes: #167 
While staging contracts on Mainnet, I realized the contract defined in NFTCollectionFactory is names NFTProviderAndCollectionFactory which collides with another contract. I assume this wasn't caught in #163 so am submitting the fix in this PR.
> Rename NFTCollectionFactory.cdc contract

- contracts/standard/ExampleNFT.cdc
- contracts/standard/ExampleNFT2.cdc
- scripts/example-nft/setup_full.cdc
- scripts/example-nft/setup_only_save.cdc
- scripts/test/test_get_all_collection_data_from_storage.cdc
- test/HybridCustody_tests.cdc
- transactions/example-nft-2/setup_full.cdc
- transactions/example-nft/setup_full.cdc
- transactions/example-nft/setup_only_save.cdc
- transactions/hybrid-custody/send_child_ft_with_parent.cdc
- transactions/hybrid-custody/send_child_nfts_with_parent.cdc
> Add example transaction transferring child NFTs from parent account
