- .gitignore
- test.sh
**NOTE**: This requires `flow-cli` version `v0.49.0` or above.
```bash
flow version
Version: v0.49.0
Commit: cfd3dc4d3594ae7648ba6a3ecbe49683192c7aa3
```
Example output:
```bash
./test.sh
Running tests...
Test results: "./test/CapabilityFactory_tests.cdc"
- PASS: testGetProviderCapability
Test results: "./test/CapabilityProxy_tests.cdc"
- PASS: testSetupProxy
- PASS: testShareExampleNFTCollectionPublic
Test results: "./test/RestrictedChildAccount_tests.cdc"
- PASS: testSetupCapabilityFactory
- PASS: testManagerSetup
- PASS: testShareAccount
- PASS: testParentBorrowCollection
- PASS: testParentWithdrawNFT
Coverage: 50.3% of statements
```
> Improve bash script for running tests with code coverage support

- scripts/hybrid-custody/get_child_addresses.cdc
- scripts/hybrid-custody/get_parent_addresses.cdc
> Query All Accounts Associated with Address

- scripts/hybrid-custody/has_child_accounts.cdc
- scripts/hybrid-custody/has_owned_accounts.cdc
- test/HybridCustody_tests.cdc
> Query whether account has child/owned accounts

- contracts/HybridCustody.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/remove_child_account.cdc
> Add removeChild txn and update method to include removeParent

- .github/workflows/integration-tests.yml
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/setup_multi_sig.cdc
> multi-sig setup transaction for child and parent

- scripts/hybrid-custody/metadata/assert_child_account_display.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/setup_child_account.cdc
- transactions/hybrid-custody/setup_child_account_with_display.cdc
> add transaction for setting child account display on creation

- scripts/example-nft-2/get_ids.cdc
- scripts/hybrid-custody/get_accessible_proxy_account_nfts.cdc
- scripts/test/test_get_accessible_proxy_nfts.cdc
- test/HybridCustody_tests.cdc
- transactions/example-nft-2/mint_to_account.cdc
> Query those NFTs that are accessible from user's ProxyAccounts 

- contracts/HybridCustody.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/set_default_manager_cap.cdc
> add ability to set a default manager capability

- contracts/CapabilityFilter.cdc
> update Filter.removeType() event conditions

- .github/workflows/integration-tests.yml
- test/HybridCustody_tests.cdc
> Fix gh action not failing properly

- contracts/HybridCustody.cdc
- flow.json
> DRAFT: [BUG] Transferring ownership does not emit an AccountUpdated event

- contracts/HybridCustody.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/misc/save_resource_to_parent_proxy_storage_slot.cdc
- transactions/hybrid-custody/remove_parent_from_child.cdc
> fail when publishing a parent if there are storage path conflicts

- contracts/HybridCustody.cdc
- transactions/hybrid-custody/onboarding/blockchain_native.cdc
- transactions/hybrid-custody/setup_multi_sig.cdc
- transactions/hybrid-custody/setup_owned_account.cdc
- transactions/hybrid-custody/setup_owned_account_with_display.cdc
> rename createChildAccount to createOwnedAccount

- contracts/HybridCustody.cdc
> chore: fix error descriptions

- contracts/CapabilityDelegator.cdc
- contracts/CapabilityFilter.cdc
- contracts/HybridCustody.cdc
- scripts/hybrid-custody/get_parent_addresses.cdc
> Comment and clean

- scripts/hybrid-custody/get_accessible_child_account_nfts.cdc
- test/HybridCustody_tests.cdc
- transactions/hybrid-custody/setup_owned_account_and_publish_to_parent.cdc
- transactions/hybrid-custody/setup_owned_account_with_display_and_publish_to_parent.cdc
> add consolidated setup & publish txns

- contracts/HybridCustody.cdc
Related: #107
Submitting as concrete point of conversation around events.
> update HybridCustody events

- contracts/factories/FTAllFactory.cdc
- flow.json
> add factory that returns a cap for all standard ft interfaces

- .github/workflows/integration-tests.yml
- scripts/factory/get_nft_provider_from_factory.cdc
- scripts/factory/get_nft_provider_from_factory_allowed.cdc
- scripts/test/add_nft_receiver_factory.cdc
- scripts/test/get_nft_receiver_factory.cdc
- scripts/test/test_get_accessible_child_nfts.cdc
- test/CapabilityDelegator_tests.cdc
- test/CapabilityFactory_tests.cdc
- test/HybridCustody_tests.cdc
- test/test_helpers.cdc
- transactions/delegator/remove_private_nft_collection.cdc
- transactions/delegator/remove_public_nft_collection.cdc
- transactions/test/add_nft_receiver_factory.cdc
- Introduces the `test/test_helpers.cdc` helper file, to contain all the helper functions used throughout the test suite.
- Removes deployment of un-necessary utility contracts (`ArrayUtils` / `StringUtils` / `AddressUtils`)
- Uses some new matchers: `Test.assertEqual` / `Test.expect` etc
- Deploys the contracts under testing, to a single admin account, for better coverage reporting.
> Update integration tests with the latest features from the Cadence testing framework

- .gitignore
- flow.json
- scripts/factory/get_nft_provider_from_factory_allowed.cdc
- test/HybridCustody_tests.cdc
Closes: #138 
Also updated a factory & filter script to accept differing addresses for filter & factory & address to pull NFT Provider from. This came out of troubleshooting on the wallet side of things and was helpful to have on hand.
> update flow.json + amend factory/filter query

- transactions/dev-setup/setup_nft_filter_and_factory_manager.cdc
- transactions/factory/setup.cdc
From the context, it should be `PublicPath` here.
> fix: factory setup transactions

- .github/workflows/integration-tests.yml
- README.md
- flow.json
- test/CapabilityFactory_tests.cdc
- test/HybridCustody_tests.cdc
- transactions/factory/setup_ft_manager.cdc
- transactions/factory/setup_nft_ft_manager.cdc
- transactions/factory/setup_nft_manager.cdc
> Add Previewnet deployment details
